<?php
    $title = $this->translate('DB Import');
    $this->headTitle($title);
	$locale = $this->plugin('translate')->getTranslator()->getLocale();
	$paginator = $this->paginator;
?>
<h2 class="text-center mt-3"><?= $this->translate('DB Import'); ?></h2>
<a class="btn btn-danger" href="<?= $this->url($this->route, ['action' => 'importall']); ?>"><?= $this->translate('Import All'); ?></a>
<div class="row px-5">
    <ol class="col-10 ml-3" start="<?= (($paginator->getCurrentPageNumber() - 1) * $paginator->getItemCountPerPage()) + 1; ?>">
<?= $this->paginationControl($paginator,
     'Sliding',
     'application/dbimport/page.phtml'); ?>
        <?php foreach ($paginator as $school): ?>
		<li><a href="<?= $this->url($this->route, ['action' => 'view', 'id' => $school['id_edbo']]); ?>"><?= $school['name_' . $locale]; ?> (IdEdbo = <?= $school['id_edbo']; ?>)</a></li>
        <?php endforeach;?>
<?= $this->paginationControl($paginator,
     'Sliding',
     'application/dbimport/page.phtml'); ?>
    </ol>
</div>