<?php
    $title = $this->translate('DB Import');
    $this->headTitle($title);
	$locale = $this->plugin('translate')->getTranslator()->getLocale();
?>
<h2 class="text-center mt-3"><?= $this->school->{'name_' . $locale}; ?></h2>
<h3 class="text-center mt-3"><?= $this->program->Name; ?></h3>
<p>Id: none | <?= $dbProgram['id']; ?></p>
<p>Id EDBO: <?= $this->program->Id; ?> | <?= $dbProgram['id_edbo']; ?></p>
<p>Name: <?= $this->program->Name; ?> | <?= $dbProgram['title']; ?></p>
<p>Number: <?= $this->program->Number; ?> | <?= $dbProgram['id_edbo']; ?></p>
<p>EnName: <?= $this->program->EnName; ?> | none</p>
<p>UniversityId: <?= $this->program->UniversityId; ?> | <?= $dbProgram['id_school']; ?></p>
<p>ExternalId: <?= $this->program->ExternalId; ?> | <?= $dbProgram['id_edbo']; ?></p>
<p>EducationBaseId: <?= $this->program->EducationBaseId; ?> | <?= $dbProgram['id_base']; ?></p>
<p>FacultetId: <?= $this->program->FacultetId; ?> | none </p>
<p>StudyTerm: <?= $this->program->StudyTerm; ?> | <?= $dbProgram['period']; ?></p>
<p>StudyDateFrom: <?= $this->program->StudyDateFrom; ?> | <?= $dbProgram['learning_start']; ?></p>
<p>StudyDateTo: <?= $this->program->StudyDateTo; ?> | <?= $dbProgram['learning_end']; ?></p>
<p>OffersTotal: <?= $this->program->OffersTotal; ?> | none</p>
<p>OffersContract: <?= $this->program->OffersContract; ?> | none</p>
<p>TicketDateFrom: <?= $this->program->TicketDateFrom; ?> | <?= $dbProgram['entrance_start']; ?></p>
<p>TicketDateTo: <?= $this->program->TicketDateTo; ?> | <?= $dbProgram['entrance_end']; ?></p>
<p>CourseStart: <?= $this->program->CourseStart; ?> | none</p>
<p>QualificationId: <?= $this->program->QualificationId; ?> | <?= $dbProgram['id_level']; ?></p>
<p>SpecialityId: <?= $this->program->SpecialityId; ?> | <?= $dbProgram['id_specialty']; ?></p>
<p>ScoreAverage: <?= $this->program->ScoreAverage; ?> | <?= $dbProgram['ave_rate']; ?></p>
<p>ScoreMax: <?= $this->program->ScoreMax; ?> | <?= $dbProgram['max_rate']; ?></p>
<p>ScoreMin: <?= $this->program->ScoreMin; ?> | <?= $dbProgram['min_rate']; ?></p>
