<?php
$title = 'Добавить заведение';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('school',array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('address'));
echo $this->formRow($form->get('phone'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('http'));
echo $this->formRow($form->get('info'));
?><label><span><?php
$areaOptions = $form->get('area')->getOptions();
echo $areaOptions['label'];
?></span><?php
echo $this->formSelect($form->get('area'));
?></label><?php
echo $this->formRow($form->get('high'));
echo $this->formRow($form->get('map'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();