<?php

$title = 'Редактировать школу';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'school',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('address'));
echo $this->formRow($form->get('phone'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('http'));
echo $this->formRow($form->get('info'));
echo $this->formRow($form->get('area'));
echo $this->formRow($form->get('high'));
echo $this->formRow($form->get('map'));
echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-primary'));
echo $this->form()->closeTag();