<?php
$paginator = $this->paginator;
if($this->high) :
    $title = $this->translate('Kharkov universities');
    $this->headTitle($title);
else :
    $title = $this->translate('Kharkov schools');
    $this->headTitle($title); ?>
<div class="d-inline-flex form-group mt-3 small">
    <form method="post">
        <label for="area">Показать район</label>
        <select class="custom-select custom-select-sm" name="area" id="area" onChange="this.form.submit();">
        <option value="0">Все</option>
    <?php
    foreach($areas as $indx => $areaName) :
        $selected = ($this->area == ($indx+1)) ? ' selected="selected"' : '';       
        ?>
        <option value="<?= ($indx+1);?>"<?= $selected;?>><?= $areaName;?></option>
    <?php endforeach; ?>
        </select>
        </label>
    </form>
</div>
<?php endif; ?>
<h1><?= $title;?></h1>
<div class="row">
    <div class="col-md-8">
        <div class="card-columns">
        <?php foreach ($paginator as $item): ?>
            <div class="card">
                <div class="card-body">
                    <a href="<?= $this->url($this->route,array('action'=>'view','id'=>$item->id)); ?>"><?= $item->name;?></a>
                <?php if(isset($username)) : ?>
                    <a class="edit" title="Редактировать" href="/edit/<?= $item->id;?>"></a>
                    <a class="delete" title="Удалить" href="/delete/<?= $item->id;?>"></a>
                <?php endif; ?>
                </div>
            </div>
        <?php endforeach;?>
        </div>
<?= $this->paginationControl($paginator,
     'Sliding',
     'school/school/page.phtml', [
         'high' => $this->high,
         'area' => $this->area
     ]); ?>
<?php if($username) : ?>
<br /><a class="btn btn-primary" href="/add/<?= $this->high; ?>">Добавить</a>

        <?php endif; ?>
    </div>    
    <div class="col-md-1"></div>
    <div class="col-md-3">
<?php if($username) : ?>
<p><a class="btn btn-primary" href="<?= $this->url('school',array('action' => 'updatenews')); ?>"><?= $this->translate('Update news'); ?></a></p>
<?php endif;
$i = $news_max;
foreach ($news['news'] as $item) :
    if($i>0) :
?>
<article class="small">
    <a class="h6" target="_blank" href="<?= $item['link']; ?>"><?= $item['title']; ?></a>
    <?= $item['description']; ?>
    <p>
    <?= $this->translate('Published'); ?>: <?= $item['pubDate']; ?> 
    <a target="_blank" href="<?= $item['link']; ?>"><?= $this->translate('Details'); ?></a></p> 
</article>
    <?php endif;
    $i--;
endforeach; ?>
<h6><a target="_blank" href="<?= $news['link']; ?>"><?= $news['title']; ?></a></h6>
    </div>
</div>