<?php
use Zend\Authentication\Storage\Session as SessionStorage;

$form = $this->form;
$form->setAttribute('action', $this->url(
    'school',
    array(
        'action' => 'login',
    )
));
$form->prepare();
echo $this->form()->openTag($form);
$form->get('login')->setAttribute('class','login');
$form->get('passwd')->setAttribute('class','login');
echo $this->formRow($form->get('login'));
echo $this->formRow($form->get('passwd'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();