<?php

if ($this->pageCount):
?>
<div class="paginationControl">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url($this->route, array(
      'action'=>'schools',
      'id'=>$this->high,
      'area'=>$this->area,
      'page' => $this->previous
  )); ?>">
    < Предыдущая
  </a> |
<?php else: ?>
  <span class="hidden">< Предыдущая</span> |
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?php echo $this->url($this->route, array(
      'action'=>'schools',
      'id'=>$this->high,
      'area'=>$this->area,
      'page' => $page
    )); ?>">
        <?php echo $page; ?>
    </a> |
  <?php else: ?>
    <strong>
    <?php echo $page; ?>
    </strong> |
  <?php endif; ?>
<?php endforeach; ?>
    
<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url($this->route, array(
      'action'=>'schools',
      'id'=>$this->high,
      'area'=>$this->area,
      'page' => $this->next
  )); ?>">
    Следующая >
  </a>
<?php else: ?>
  <span class="hidden">Следующая ></span>
<?php endif; ?>
</div>
<?php endif; ?>
