<?php
echo $this->headLink()->prependStylesheet($this->basePath() . 'https://use.fontawesome.com/releases/v5.7.2/css/all.css');
$paginator = $this->paginator;
if($this->high) :
    $title = $this->translate('Kharkov universities');
    $this->headTitle($title);
else :
    $title = $this->translate('Kharkov schools');
    $this->headTitle($title); ?>
    <form method="post">
        <label class="small">
        <span>Показать район</span>
        <select name="area" id="area" onChange="this.form.submit();">
        <option value="0">Все</option>
    <?php
    foreach($areas as $indx => $areaName) :
        $selected = ($this->area == ($indx+1)) ? 'selected="selected"' : '';       
        ?>
        <option value="<?= ($indx+1);?>" <?= $selected;?>><?= $areaName;?></option>
    <?php endforeach; ?>
        </select>
        </label>
    </form>
<?php endif; ?>
<h1><?= $title;?></h1>
<ol start="<?= (($paginator->getCurrentPageNumber()-1)*($paginator->getItemCountPerPage())+1);?>">
<?php foreach ($paginator as $item): ?>
<li>
    <a href="<?= $this->url($this->route,array('action'=>'view','id'=>$item->id)); ?>"><?= $item->name;?></a>
<?php if(isset($username)) : ?>
    <a class="fa fa-edit" title="Редактировать" href="/edit/<?= $item->id;?>"></a>
    <a class="fa fa-trash-alt" title="Удалить" href="/delete/<?= $item->id;?>"></a>
<?php endif; ?>

</li>
<?php endforeach;?>
</ol>
<?= $this->paginationControl($paginator,
     'Sliding',
     'school/school/page.phtml', [
         'high' => $this->high,
         'area' => $this->area
     ]);
if(isset($username)) : ?>
<br /><a class="btn btn-primary my-3" href="/add/<?= $this->high; ?>">Добавить</a>
<?php endif; ?>
