<?php
    $title = $this->translate('University search');
    $this->headTitle($title);
	$locale = $this->plugin('translate')->getTranslator()->getLocale();
?>
<h2 class="text-center mt-3"><?= $this->translate('University search'); ?></h2>
	<form class="border border-light p-3" method="post" action="/search/subject">
		<label for="level"><?= $this->translate('Select Level'); ?></label>
		<select class="custom-select custom-select-md" name="level" id="level">
			<?php foreach($this->levels as $level) :
			$selected = ($level->id == 2) ? ' selected="selected"' : '';
			?>
			<option value="<?= $level->id; ?>"<?= $selected; ?>><?= $level->{'title_'.$locale}; ?></option>
			<?php endforeach; ?>
		</select>
		<label for="form"><?= $this->translate('Select Learning Form'); ?></label>
		<select class="custom-select custom-select-md" name="form" id="form">
		    <option value="0" selected><?= $this->translate('Any'); ?></option>
			<?php foreach($this->forms as $form) : ?>
			<option value="<?= $form->id; ?>"><?= $form->title; ?></option>
			<?php endforeach; ?>
		</select>
		<button type="submit" class="btn btn-primary mt-3"><?= $this->translate('Next'); ?> &raquo;</button>
	</form>
	<?php if($this->error) : ?>
    <div class="alert alert-danger" role="alert">
    <?= $this->error; ?>
    </div>
    <?php endif; ?>
    <p class="my-4">&nbsp;</p>