<?php
    $title = $this->translate('University search');
    $this->headTitle($title);
	$locale = $this->plugin('translate')->getTranslator()->getLocale();
?>
<h1 class="text-center mt-3"><?= $this->title; ?></h1>
	<form method="post" action="/search/view" enctype="multipart/form-data">
		<label for="level"><?= $this->translate('Select Level'); ?></label>
		<select class="custom-select custom-select-md" name="level" id="level">
			<?php foreach($this->levels as $level) :
			//$selected = ($level->id == ($index+1)) ? ' selected="selected"' : '';
			?>
			<option value="<?= $level->id; ?>"<?= '' /*$selected;*/?>><?= $level->{'title_'.$locale}; ?></option>
			<?php endforeach; ?>
		</select>
		<label for="form"><?= $this->translate('Select Learning Form'); ?></label>
		<select class="custom-select custom-select-md" name="form" id="form">
		    <option value="0" selected><?= $this->translate('Any'); ?></option>
			<?php foreach($this->forms as $form) :
			//$selected = ($level->id == ($index+1)) ? ' selected="selected"' : '';
			?>
			<option value="<?= $form->id; ?>"<?= '' /*$selected;*/?>><?= $form->title; ?></option>
			<?php endforeach; ?>
		</select>
		<div class="form-group">
			<label class="form-check-label" for="subject"><?= $this->translate('Select your subjects'); ?></label>
			<select name="subjects[]" id="subjects" class="custom-select" size="<?= count($this->subjects); ?>" multiple>
			<?php foreach($this->subjects as $subject) : ?>	
				<option value="<?= $subject->id; ?>"><?= $subject->title; ?></option>
			<?php endforeach; ?>
			</select>
		</div>
		<button type="submit" class="btn btn-primary"><?= $this->translate('Find'); ?></button>
	</form>

