<?php
    $title = $this->translate('Enter your rating');
    $this->headTitle($title);
	$locale = $this->plugin('translate')->getTranslator()->getLocale();
?>
<h2 class="text-center mt-3"><?= $this->translate('Enter your rating'); ?></h2>
<div class="container">
	<div class="row">
		<div class="col">
			<form class="border border-light p-3" method="post" action="/search/view" id="subjects" enctype="multipart/form-data">
				<?php foreach($this->subjects as $subject) : ?>
<div class="form-group">		
					<label for="subject[<?= $subject->id ?>]"><?= $subject->title; ?></label>
					<input type="number" min="0" max="200" placeholder="<?= $this->translate('Enter your rating'); ?>" class="custom-select custom-select-md" id="subject[<?= $subject->id ?>]" name="subject[<?= $subject->id ?>]" />
				</div>
				<?php endforeach; ?>
<input type="hidden" id="form" value="<?= $this->form; ?>" name="form" />
				<input type="hidden" id="level" value="<?= $this->level; ?>" name="level" />
				<button class="btn btn-info mr-3" onclick="window.history.back();">&laquo; <?= $this->translate('Back'); ?></button>
				<button form="subjects" type="submit" class="btn btn-primary"><?= $this->translate('Find'); ?> &raquo;</button>
			</form>					
		</div>
	</div>
</div>
<p class="my-4">&nbsp;</p>