<?php
    $title = $this->translate('University search');
    $this->headTitle($title);
	$locale = $this->plugin('translate')->getTranslator()->getLocale();
?>
<h2 class="text-center mt-3"><?= $this->translate('University search'); ?></h2>
	<form class="border border-light p-3" method="post" action="/search/rating" enctype="multipart/form-data">
		<div class="form-group">
			<label class="form-check-label" for="subject"><?= $this->translate('Select your subjects'); ?></label>
			<select name="subjects[]" id="subjects" class="custom-select" size="<?= count($this->subjects); ?>" multiple>
			<?php foreach($this->subjects as $subject) : 	
				$selected = ($subject['id'] == 6) ? ' selected="selected"' : ''; ?>
				<option value="<?= $subject['id']; ?>"<?= $selected; ?>><?= $subject['title']; ?></option>
			<?php endforeach; ?>
			</select>
		</div>
		<a class="btn btn-info mr-3" href="/search">&laquo; <?= $this->translate('Back'); ?></a>		
		<button type="submit" class="btn btn-primary"><?= $this->translate('Next'); ?> &raquo;</button>
	</form>
	<?php if($this->error) : ?>
    <div class="alert alert-danger" role="alert">
    <?= $this->error; ?>
    </div>
    <?php endif; ?>
    <p class="my-4">&nbsp;</p>