<?php
    $title = $this->translate('Search results');
    $this->headTitle($title);
	$locale = $this->plugin('translate')->getTranslator()->getLocale();
?>
<h2 class="text-center mt-3"><?= $this->title; ?></h2>
<?php if($this->search && is_array($this->search)) :
foreach($this->search as $program) : ?>
<div class="card border-secondary mb-3">
    <div class="card-header text-white bg-secondary"><?= $this->translate('Specialty'); ?>: <?= $program['specialty_title']; ?></div>
	<div class="card-body">
	    <h5 class="card-title"><?= $this->translate('Education Program'); ?>: <?= $program['title']; ?></h5>
	    <p class="card-text">
<?= $this->translate('Education Form'); ?>: <?= $program['form_title']; ?></p>
	    <h5 class="card-title"><?= $this->translate('Universities'); ?>:</h5>
	    <?php foreach($program['universities'] as $university) : ?>
	    <p class="card-text"><a target="_blank" href="/view/<?= $university['id']; ?>"><?= $university['name_'.$locale]; ?></a></p>
	    <?php endforeach; ?>
	</div>
</div>
<?php endforeach;
else : ?>
<p><?= $this->translate('Not found'); ?></p>
<?php endif; ?>
	<a class="btn btn-info mr-3" href="/search">&laquo; <?= $this->translate('Back'); ?></a>
