<?php
    $title = $this->translate('Specialties');
    $this->headTitle($title);
	$locale = $this->plugin('translate')->getTranslator()->getLocale();
if($this->api) :
?>
<textarea class="w-100 mt-5 p-3" rows="24">
<?= $this->api == 'json' ? Zend\Json\Json::prettyPrint(Zend\Json\Json::fromXml($this->branchesDOM->saveXML(), false)) : $this->branchesDOM->saveXML(); ?>
</textarea>
<?php else : ?>
<h2 class="text-center my-3 mx-5"><?= $this->translate('Branches'); ?></h2>
<div class="table-responsive">
<table class="table table-sm table-striped">
	<thead>
		<tr>
			<th scope="col"><?= $this->translate('Branch Code'); ?></th>
			<th scope="col"><?= $this->translate('Branch Title'); ?></th>
			<th scope="col"><?= $this->translate('Specialty Code'); ?></th>
			<th scope="col"><?= $this->translate('Specialty Title'); ?></th>
		</tr>
	</thead>
<?php
$branches = $this->branchesDOM->getElementsByTagName('branch');
foreach($branches as $branch) :
	$specialties = $branch->getElementsByTagName('specialty');
	$rowspan = $specialties->count();
	$counter = 0;
	foreach($specialties as $specialty) :
?>
		<tr>
	<?php if(!$counter) : ?>
			<td rowspan="<?= $rowspan; ?>"><?= $branch->getAttribute('code'); ?></td>
			<td rowspan="<?= $rowspan; ?>"><?= $branch->firstChild->textContent; ?></td>		
	<?php endif; ?>
	<?php $counter++; ?>	
			<td><?= $specialty->getAttribute('code'); ?></td>
			<td><a href="<?= $this->url('specialty', ['action' => 'view', 'id' => explode('_', $specialty->getAttribute('id'))[1]]); ?>"><?= $specialty->textContent; ?></a></td>
		</tr>
<?php
	endforeach;
endforeach;
?>
	</tbody>	
</table>
</div>
<?php endif;