<?php
    $title = $this->translate('Specialty');
    $this->headTitle($title);
	$locale = $this->plugin('translate')->getTranslator()->getLocale();
?>
<h4 class="text-center my-3 mx-5"><?= $title ?> <?= sprintf("%02d", $this->branch->code); ?><?= $this->specialty->code; ?> <?= $this->specialty->title; ?></h4>
<h5 class="text-center"><?= $this->translate('Branch Title'); ?><br/><?= sprintf("%02d", $this->branch->code); ?> <?= $this->branch->title; ?></h5>
<?php if($this->schools) : ?>
<h5 class="text-center"><?= $this->translate('Universities'); ?>:</h5>
<div class="card-columns">
	<?php foreach($this->schools as $university) : ?>
	<div class="card">
		<div class="card-body w-100 pt-0">
			<a class="align-bottom" href="<?= $this->url('schools', ['action' => 'view', 'id' => $university->id]); ?>"><h5><span class="badge badge-pill btn btn-outline-primary float-right px-3 mr-0"><?= $university->shortname; ?></span></h5></a>
			<a class="align-bottom" href="<?= $this->url('schools', ['action' => 'view', 'id' => $university->id]); ?>"><img class="card-img-top w-25" src="<?= $university->logo; ?>" alt="logo" /></a>
			<a class="align-bottom" href="<?= $this->url('schools', ['action' => 'view', 'id' => $university->id]); ?>"><?= $university->{'name_'.$this->plugin('translate')->getTranslator()->getLocale()}; ?></a>
		</div>
	</div>
	<?php endforeach; ?>
</div>
<?php endif; ?>
<p class="my-5">&nbsp;</p>