<?php
echo $this->headLink()->prependStylesheet($this->basePath() . 'https://use.fontawesome.com/releases/v5.7.2/css/all.css');
echo $this->inlineScript()->appendFile('/js/import.js');
$title = $this->translate('Kharkov universities') . ' from EDBO';
$this->headTitle($title);
?>
<div class="d-inline-flex form-group mt-3 small">
    <form>
        <label for="area"><?= $this->translate('Select Region'); ?></label>
        <select class="custom-select custom-select-sm" name="region" id="region" onchange="this.form.submit();">
<?php
foreach($this->regions as $region) :
	$selected = ($region->id_edbo == $this->id) ? 'selected="selected"' : '';    
?>
            <option <?= $selected; ?> value="<?= $region->id_edbo; ?>" id="<?= $region->id; ?>"><?= $region->title; ?></option>
<?php endforeach; ?>
        </select>
    </form>        
</div>
<h1 class="text-center"><?= $title;?></h1>
<div class="row">
    <div class="col">
        <button class="btn btn-primary btn-import-selected" disabled="true">Import selected</button>
        <button class="btn btn-danger ml-3">Import All</button>
    </div>
</div>
<div class="table-responsive">
<table class="table table-striped">
	<thead>
		<tr>
			<th><input id="select_all_top" class="university_select" type="checkbox" title="Select All" /></th>
			<th><?= $this->translate('ID'); ?></th>
			<th><?= $this->translate('Name'); ?></th>
			<th><?= $this->translate('Action'); ?></th>
			<th><?= $this->translate('ID EDBO'); ?></th>
			<th><?= $this->translate('Type'); ?></th>
		</tr>
	</thead>
    <tbody>
	<form method="post">
<?php foreach($this->json as $university) : ?>
        <tr>
			<td><input id="select_<?= $university->university_id; ?>" class="university_select" type="checkbox" name="university_id[<?= $university->university_id; ?>]" /></td>
<?php $school = $this->table->getSchoolByIdEdbo($university->university_id); ?>
            <td><?= $school ? $school->id : '-'; ?></td>
            <td><?= $university->university_name; ?></td>
            <td><a class="fas fa-download pr-3 update" title="Import from EDBO to local DB" href="<?= $this->url('import', ['action'=>'import', 'id' => $university->university_id], ['query' => ['region' => $this->id]]); ?>"></a></td>
			<td><?= $university->university_id; ?></td>
            <td><?= $university->education_type_name; ?></td>
        </tr>
<?php endforeach; ?>
	</form>
	<tr>
		<th colspan="6"><input id="select_all_bottom" class="university_select" type="checkbox" title="Select All" /></th>
	</tr>
    </tbody>
</table>
</div>
<div class="row">
    <div class="col">
        <button class="btn btn-primary btn-import-selected" disabled="true">Import selected</button>
        <button class="btn btn-danger ml-3">Import All</button>
    </div>
</div>