<?php
echo $this->headLink()->prependStylesheet($this->basePath() . 'https://use.fontawesome.com/releases/v5.7.2/css/all.css');
//echo $this->inlineScript()->appendFile('/js/load_json.js');
$title = $this->translate('Kharkov universities') . ' from EDBO';
$this->headTitle($title);
?>
<div class="d-inline-flex form-group mt-3 small">
    <form method="post">
        <label for="area"><?= $this->translate('Select Region'); ?></label>
        <select class="custom-select custom-select-sm" name="region" id="region" onchange="this.form.submit();">
<?php
foreach($this->regions as $region) :
	$selected = ($region->id_edbo == $this->id) ? 'selected="selected"' : '';    
?>
            <option <?= $selected; ?> value="<?= $region->id_edbo; ?>" id="<?= $region->id; ?>"><?= $region->title; ?></option>
<?php endforeach; ?>
        </select>
    </form>        
</div>
<h1 class="text-center"><?= $title;?></h1>
<div class="table-responsive">
<table class="table table-striped">
	<thead>
		<tr>
			<th>&nbsp;</th>
			<th><?= $this->translate('ID'); ?></th>
			<th><?= $this->translate('Name'); ?></th>
			<th><?= $this->translate('ID EDBO'); ?></th>
			<th><?= $this->translate('Type'); ?></th>
		</tr>
	</thead>
    <tbody>
<?php foreach($this->json as $university) : ?>
        <tr>
			<td><input type="checkbox" name="university_id[<?= $university->university_id; ?>]" /></td>
            <td>-</td>
            <td><?= $university->university_name; ?></td>
			<td><?= $university->university_id; ?></td>
            <td><?= $university->education_type_name; ?></td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>
</div>
