<?php
echo $this->headLink()->prependStylesheet($this->basePath() . 'https://use.fontawesome.com/releases/v5.7.2/css/all.css');
echo $this->inlineScript()->appendFile('/js/import.js');
$title = $this->translate('Kharkov universities') . ' from EDBO';
$this->headTitle($title);
?>
<div class="d-inline-flex form-group mt-3 small">
    <form>
        <label for="area"><?= $this->translate('Select Region'); ?></label>
        <select class="custom-select custom-select-sm" name="region" id="region" onchange="this.form.submit();">
<?php
foreach($this->regions as $region) :
	$selected = ($region->id_edbo == $this->id) ? 'selected="selected"' : '';    
?>
            <option <?= $selected; ?> value="<?= $region->id_edbo; ?>" id="<?= $region->id; ?>"><?= $region->title; ?></option>
<?php endforeach; ?>
        </select>
    </form>        
</div>
<h1 class="text-center"><?= $title;?></h1>
<div class="row mb-3">
    <div class="col">
        <button id="select_form_submit_top" class="btn btn-primary btn-import-selected" disabled="true" form="university_select_form">Import selected</button>
        <button id="import_all_top" class="btn btn-danger ml-3" href="">Import All</button>
    </div>
</div>

<div class="table-responsive">
<table id="json-table" class="table table-striped">
	<thead>
		<tr>
			<th><input form="university_select_form" id="select_all_top" class="university_select" type="checkbox" title="Select All" /></th>
			<th id="th-id"><?= $this->translate('ID'); ?><i class="none"></i></th>
			<th id="th-university_name"><?= $this->translate('Name'); ?><i class="none"></i></th>
			<th><?= $this->translate('Action'); ?></th>
			<th id="th-university_id"><?= $this->translate('ID EDBO'); ?><i class="none"></i></th>
			<th id="th-education_type_name"><?= $this->translate('Type'); ?><i class="none"></i></th>
		</tr>
	</thead>

	<tbody>
		<tr class="d-none">
			<td id="json-string" colspan="3"><?= $this->jsonString; ?></td>
			<td id="schools-string" colspan="3"><?= $this->schoolsString; ?></td>
		<tr>
	</tbody>
</table>
	<form method="post" id="university_select_form" action="<?= $this->url('import', ['action'=>'import'], ['query' => ['region' => $this->id]]); ?>"></form>
</div>
<div class="row">
    <div class="col">
        <button id="select_form_submit_bottom" class="btn btn-primary btn-import-selected" disabled="true">Import selected</button>
        <button id="import_all_bottom" class="btn btn-danger ml-3">Import All</button>
    </div>
</div>