<?php
$config = $this->__helpers->getServiceLocator()->get('config');
echo $this->doctype();
?>

<html lang="<?= $config['language']; ?>">
<head>
<?= $this->headTitle('')->setSeparator(' - ')->setAutoEscape(false) ?>
    
<meta charset="utf-8">    
<?= $this->headMeta()
->appendName('viewport', 'width=device-width, initial-scale=1.0')
->appendName('description', $config['description'])
->appendName('keywords', $config['description'])
->appendName('viewport', 'width=device-width, initial-scale=1.0')        
->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
->appendHttpEquiv('pragma', 'no-cache')
->appendHttpEquiv('Cache-Control', 'no-cache')
->appendHttpEquiv('Content-language', $config['language'])        
?>

<!-- Styles -->
<?= $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
->prependStylesheet($this->basePath() . 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css')        
//->prependStylesheet($this->basePath() . '/css/style.css')
?>
<!-- Scripts -->
<?= $this->headScript()
//->prependFile($this->basePath() . '/js/bootstrap.min.js')
//->prependFile($this->basePath() . '/js/jquery.min.js')
//->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
//->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
; ?>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="<?= $this->url('school') ?>">
            <img src="/img/favicon.ico" width="30" height="30" alt="logo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url('school',array('action' => 'schools', 'id' => 0));?>"><?= $this->translate('Schools') ?></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url('school',array('action' => 'schools', 'id' => 1));?>"><?= $this->translate('Universities') ?></a>
                </li>
            <?php
            if(isset($username)) {
                echo('<li class="nav-item"><a class="nav-link" href="'.$this->url("school",array("action" => "updatenews")).'">'.$this->translate('Update news').'</a></li>');
            }
            ?>
            </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
                </form>
        </div>
    </nav>
    <div class="container">  
        <div class="content">
            <div class="main">
            <?= $this->content; ?>                
            </div>
            <div class="band"></div>
            <div class="wrap"></div>
        </div> <!-- /content -->
    </div> <!-- /container -->
    
<footer class="navbar navbar-dark bg-dark text-light justify-content-center">
    <p>&copy; <?= date('Y') ?> <a href="mailto://<?= $config['ServerAdmin'];?>">SuM</a> <?= $this->translate('All rights reserved.') ?></p>
    <p><?php /*include_once('public_html/counters.html');*/ ?></p>
</footer>
<?php echo $this->inlineScript()
->prependFile($this->basePath() . 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js')
->prependFile($this->basePath() . 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js')          
->prependFile($this->basePath() . 'https://code.jquery.com/jquery-3.3.1.slim.min.js')
?>
    
</body>
</html>
