<?php
use Zend\Authentication\AuthenticationService;

$config = $this->__helpers->getServiceLocator()->get('config');
echo $this->doctype();
?>

<html lang="<?= $config['language']; ?>">
<head>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-137600283-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-137600283-1');
</script>

<?= $this->headTitle('')->setSeparator(' - ')->setAutoEscape(false) ?>
    
<meta charset="utf-8">    
<?= $this->headMeta()
->appendName('viewport', 'width=device-width, initial-scale=1.0')
->appendName('description', $config['description'])
->appendName('keywords', $config['description'])
->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
//->appendHttpEquiv('pragma', 'no-cache')
//->appendHttpEquiv('Cache-Control', 'no-cache')
//->appendHttpEquiv('Content-language', $config['language'])        
?>

<!-- Styles -->
<?= $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
->prependStylesheet($this->basePath() . 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css') ?>
<!-- Scripts -->
<?= $this->headScript()
; ?>

</head>
<body class="h-100">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="<?= $this->url('schools') ?>">
            <img src="/img/favicon.ico" width="30" height="30" alt="logo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url('schools',array('action' => 'index', 'id' => 0));?>"><?= $this->translate('Schools'); ?></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url('schools',array('action' => 'index', 'id' => 1));?>"><?= $this->translate('Universities'); ?></a>
                </li>
                <?php
                $auth = new AuthenticationService();
                if($auth->hasIdentity()) : ?>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="" role="button" aria-haspopup="true" aria-expanded="false"><?= $this->translate('Adminitration'); ?></a>
                    <div class="dropdown-menu navbar-inverse bg-dark">
                        <a class="dropdown-item text-secondary" href="/admin/updateNews"><?= $this->translate('Update news') ?></a>
                        <a class="dropdown-item text-secondary" href="<?= $this->url('admin', array('action' => 'index'));?>"><?= $this->translate('Edit schools'); ?></a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item text-secondary" href="/logout"><?= $this->translate('Logout'); ?></a>
                    </div>
                </li>                
                <?php endif; ?>
            </ul>
                <form method="post" class="form-inline my-2 my-lg-0" action="/search" id="search">
                    <input class="form-control mr-sm-2" type="search" placeholder="<?= $this->translate('Search'); ?>" aria-label="Search" name="search">
                    <button class="btn btn-outline-primary my-2 my-sm-0" type="submit"><?= $this->translate('Search'); ?></button>
                </form>
        </div>
    </nav>
    <div class="container-fluid">  
        <div class="content">
            <div class="main">
            <?= $this->content; ?>                
            </div>
            <div class="band"></div>
            <div class="wrap mb-5"></div>
        </div> <!-- /content -->
    </div> <!-- /container-fluid -->
    
<footer class="navbar navbar-dark bg-dark text-light fixed-bottom justify-content-center">
    <p>&copy; 2013-<?= date('Y') ?> <?= $this->translate('All rights reserved.'); ?> <a href="mailto://<?= $config['ServerAdmin'];?>"><?= $config['ServerAdmin'];?></a></p>
    <p><?php /*include_once('public_html/counters.html');*/ ?></p>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>
