<?php
use Zend\Authentication\AuthenticationService;

$config = $this->__helpers->getServiceLocator()->get('config');
echo $this->doctype();
?>

<html lang="<?= $config['language']; ?>">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<?= $this->headMeta()
->appendName('viewport', 'width=device-width, initial-scale=1.0')
->appendName('description', $config['description'])
->appendName('keywords', $config['description'])
->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
->appendHttpEquiv('pragma', 'no-cache')
->appendHttpEquiv('Cache-Control', 'no-cache')
->appendHttpEquiv('Content-language', $config['language'])        
?>

<?= $this->headTitle('')->setSeparator(' - ')->setAutoEscape(false) ?>
<?php $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')); ?>

<!-- Styles -->
<?= $this->headLink()->appendStylesheet( 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css'); ?>
<!-- Scripts -->
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-137600283-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-137600283-1');
</script>
<?= $this->headScript()
	->appendFile('/js/jquery-3.4.1.min.js')
    ->appendFile('https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js')
    ->appendFile('https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js');
?>

</head>
<body class="h-100">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="<?= $this->url('schools') ?>">
            <img src="/img/favicon.ico" width="30" height="30" alt="logo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url('schools',array('action' => 'index', 'id' => 0));?>"><?= $this->translate('Schools'); ?></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url('schools',array('action' => 'index', 'id' => 1));?>"><?= $this->translate('Universities'); ?></a>
                </li>
				<li class="nav-item">
                    <a class="nav-link" href="<?= $this->url('specialty',array('action' => 'index'));?>"><?= $this->translate('Specialties'); ?></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url('search',array('action' => 'index'));?>"><?= $this->translate('Entrants calculator'); ?></a>
                </li>
                <?php
                $auth = new AuthenticationService();
                if($auth->hasIdentity()) : ?>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="" role="button" aria-haspopup="true" aria-expanded="false"><?= $this->translate('Administration'); ?></a>
                    <div class="dropdown-menu navbar-inverse bg-dark">
                        <a class="dropdown-item text-secondary" href="/admin/updateNews"><?= $this->translate('Update news') ?></a>
                        <a class="dropdown-item text-secondary" href="<?= $this->url('admin', ['action' => 'index', 'id' => intval(!$this->high) ]);?>"><?= $this->high ? $this->translate('Edit schools') : $this->translate('Edit universities') ?></a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item text-secondary" href="/logout"><?= $this->translate('Logout'); ?></a>
                    </div>
                </li>                
                <?php endif; ?>
            </ul>
                <form method="post" class="form-inline my-2 my-lg-0" action="<?= $this->url('schools', ['action'=>'find']); ?>" id="search">
                    <input class="form-control mr-sm-2" type="search" placeholder="<?= $this->translate('Search'); ?>" aria-label="Search" name="search">
                    <button class="btn btn-outline-primary my-2 my-sm-0" type="submit"><?= $this->translate('Search'); ?></button>
                </form>
        </div>
    </nav>
    <div class="container-fluid">  
        <div class="content">
            <div class="main">
            <?= $this->content; ?>                
            </div>
            <div class="band"></div>
            <div class="wrap mb-5"></div>
        </div> <!-- /content -->
    </div> <!-- /container-fluid -->
    
<footer class="navbar navbar-dark bg-dark text-light fixed-bottom justify-content-between">
    <div>&copy; 2013-<?= date('Y') ?> <?= $this->translate('All rights reserved.'); ?> <a href="mailto://<?= $config['ServerAdmin'];?>"><?= $config['ServerAdmin'];?></a></div>
    <div><?php /*include_once('public_html/counters.html');*/ ?>
        <a class="btn btn-outline-primary btn-sm" href="?locale=uk">UK</a>
        <a class="btn btn-outline-primary btn-sm" href="?locale=en">EN</a>
        <a class="btn btn-outline-primary btn-sm" href="?locale=ru">RU</a>
    </div>
</footer>
</body>
</html>
