<?php
$title = $this->translate('Add institution');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin', array('action' => 'add')));
$inputs = [
    'name' => $form->get('name')->setLabel($this->translate('Name')),
    'shortname' => $form->get('shortname')->setLabel($this->translate('Short Name')),
    'address' => $form->get('address')->setLabel($this->translate('Address')),
    'phone' => $form->get('phone')->setLabel($this->translate('Phone')),
    'email' => $form->get('email'),
    'http' => $form->get('http'),
    'info' => $form->get('info')->setLabel($this->translate('Information')),
    'area' => $form->get('area')->setLabel($this->translate('Area')),
    'high' => $form->get('high')->setLabel($this->translate('Is an University'))->setAttribute('class', 'form-check'),
    'map' => $form->get('map')->setLabel($this->translate('Map')),
    'logo' => $form->get('logo')->setLabel($this->translate('Logo')),
    'visible' => $form->get('visible')->setLabel($this->translate('Visible')),
];
$form->prepare();
?>
<?= $this->form()->openTag($form); ?>
<?=  $this->formHidden($form->get('id')); ?>

<?php foreach($inputs as $input) : ?>
    <?= $this->formLabel($input) ?>
    <?= $this->formElement($input->setAttribute('class', 'form-control')) ?>
    <?= $this->formElementErrors()->render($input, ['class' => 'help-block']) ?>
<?php
endforeach;
$inputs['submit'] = $form->get('submit');
$inputs['submit']->setAttribute('class', 'btn btn-primary my-3');
?>
<?= $this->formSubmit($inputs['submit']); ?>
<?= $this->formHidden($form->get('id')); ?>
<?= $this->form()->closeTag(); ?>
