<?php
$title = $this->translate('Add institution');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin', array('action' => 'add')));
$inputs = [
    'name_uk' => $form->get('name_uk')->setLabel($this->translate('Name', null, 'uk').' (uk)'),
    'name_en' => $form->get('name_en')->setLabel($this->translate('Name', null, 'en').' (en)'),
    'name_ru' => $form->get('name_ru')->setLabel($this->translate('Name', null, 'ru').' (ru)'),
    'shortname' => $form->get('shortname')->setLabel('Short Name'),
    'address' => $form->get('address')->setLabel('Address'),
    'phone' => $form->get('phone')->setLabel('Phone'),
    'email' => $form->get('email'),
    'http' => $form->get('http'),
    'info' => $form->get('info')->setLabel('Information'),
    'area' => $form->get('area')->setLabel('Area'),
    'high' => $form->get('high')->setLabel('Is an University')->setAttribute('class', 'form-check'),
    'map' => $form->get('map')->setLabel('Map'),
    'logo' => $form->get('logo')->setLabel('Logo'),
    'visible' => $form->get('visible')->setLabel('Visible'),
];
$form->prepare();
?>
<?= $this->form()->openTag($form); ?>
<?=  $this->formHidden($form->get('id')); ?>

<?php foreach($inputs as $input) : ?>
    <?= $this->formLabel($input) ?>
    <?= $this->formElement($input->setAttribute('class', 'form-control')) ?>
    <?= $this->formElementErrors()->render($input, ['class' => 'help-block']) ?>
<?php
endforeach;
$inputs['submit'] = $form->get('submit');
$inputs['submit']->setAttribute('class', 'btn btn-primary my-3');
?>
<?= $this->formSubmit($inputs['submit']); ?>
<?= $this->formHidden($form->get('id')); ?>
<?= $this->form()->closeTag(); ?>
<p class="my-3">&nbsp;</p>