<?php
$title = 'Добавить заведение';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin', array('action' => 'add')));
$inputs = [
    'name' => $form->get('name'),
    'address' => $form->get('address'),
    'phone' => $form->get('phone'),
    'email' => $form->get('email'),
    'http' => $form->get('http'),
    'info' => $form->get('info'),
    'area' => $form->get('area'),
    'high' => $form->get('high'),
    'map' => $form->get('map'),
    'logo' => $form->get('logo'),
];
$form->prepare();
?>
<?= $this->form()->openTag($form); ?>
<?=  $this->formHidden($form->get('id')); ?>

<?php foreach($inputs as $input) : ?>
    <?= $this->formLabel($input) ?>
    <?= $this->formElement($input->setAttribute('class', 'form-control')) ?>
    <?= $this->formElementErrors()->render($input, ['class' => 'help-block']) ?>
<?php
endforeach;
$inputs['submit'] = $form->get('submit');
$inputs['submit']->setAttribute('class', 'btn btn-primary my-3');
?>
<?= $this->formSubmit($inputs['submit']); ?>
<?= $this->formHidden($form->get('id')); ?>
<?= $this->form()->closeTag(); ?>
