<?php
$title = $this->translate('Delete comment');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p><?= $this->translate('Are you sure to delete a comment of user'); ?> 
    <?php
    echo $this->escapeHtml($comment->author.' - \'');
    echo $this->escapeHtml($comment->text).'?'; ?>'
</p>
<?php
$url = $this->url(
    'schools/admin',
    array(
    'action' => 'delcomment',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo $comment->id; ?>" />
    <input class="btn btn-danger my-3 mr-1" type="submit" name="del" value="Да" />
    <input class="btn btn-secondary" type="submit" name="del" value="Нет" />
</div>
</form>