<?php

$title = 'Удалить заведение';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Вы действительно хотите удалить
    '<?php echo $this->escapeHtml($school->name).'?'; ?>'
</p>
<?php
$url = $this->url('admin',array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $school->id; ?>" />
    <input class="btn btn-danger my-3 mr-1" id="submitbutton" type="submit" name="del" value="Да" />
    <input class="btn btn-secondary" id="cancelbutton" type="submit" name="del" value="Нет" />
</div>
</form>