<?php
$title = $this->translate('Edit school');
$this->headTitle($title);
?>
<h1 class='text-center'><?= $this->escapeHtml($title); ?></h1>
<div class="row">
    <div id="json" class="col border border-secondary m-3 p-3" style="display: none;"></div>
</div>
<?php
$schoolForm = $this->schoolForm;
$schoolForm->setAttribute('action', $this->url('admin',['action' => 'edit', 'id'     => $this->id]));
$inputs = [
	'id_edbo' => $schoolForm->get('id_edbo')->setLabel('ID EDBO'),
	'id_region' => $schoolForm->get('id_region'),
    'name_uk' => $schoolForm->get('name_uk')->setLabel($this->translate('Name', null, 'uk').' (uk)'),
    'name_en' => $schoolForm->get('name_en')->setLabel($this->translate('Name', null, 'en').' (en)'),
    'name_ru' => $schoolForm->get('name_ru')->setLabel($this->translate('Name', null, 'ru').' (ru)'),
    'shortname' => $schoolForm->get('shortname')->setLabel('Short Name'),
    'address' => $schoolForm->get('address')->setLabel('Address'),
    'phone' => $schoolForm->get('phone')->setLabel('Phone'),
    'email' => $schoolForm->get('email'),
    'http' => $schoolForm->get('http'),
    'info' => $schoolForm->get('info')->setLabel('Information'),
    'area' => $schoolForm->get('area')->setLabel('Area'),
    'high' => $schoolForm->get('high')->setLabel('Is an University'),
    'map' => $schoolForm->get('map')->setLabel('Map'),
    'logo' => $schoolForm->get('logo')->setLabel('Logo'),
    'visible' => $schoolForm->get('visible')->setLabel('Visible'),
];
$schoolForm->prepare();
if($inputs['high']->getValue() && $this->specialtyDOM) :
?>
<div class="container-fluid m-1 p-3 border border-light">
	<div class="row">	
		<div class="col">
			<h3><?= $this->translate('Specialties'); ?></h3>
		</div>
	</div>
	
<?php
$branches = $this->specialtyDOM->getElementsByTagName('branch');
foreach($branches as $branch) :
?>
	<div class="row" id="specialities">		
		<div class="col">
			<h4><?= $this->translate('Branch Title'); ?>: <?= $branch->getAttribute('code'); ?> <?= $branch->firstChild->textContent; ?></h4>
		</div>			
	<?php
	$specialties = $branch->getElementsByTagName('specialty');
	foreach($specialties as $specialty) :
	?>				
		<h5 class="d-block w-100 mx-3"><?= $this->translate('Specialty Title'); ?>: <?= $specialty->getAttribute('code'); ?> <?= $specialty->firstChild->textContent; ?></h5>
			<div class="card-columns">
					
		<?php
		$programs = $specialty->getElementsByTagName('program');
		foreach($programs as $program) :
		?>
				<div class="card mx-2 alert alert-primary alert-dismissible fade show" role="alert">
					<div class="card-body p-0">
						<h6 class="card-title">
							<?php $id = explode('_', $program->getAttribute('id'))[1]; ?>
							<a href="<?= $this->url('program', ['action' => 'edit', 'id' => $id]) ?>"><?= $this->translate('Education Program'); ?>: <span class="font-weight-bold"><?= $program->firstChild->textContent; ?></span></a>
						</h6>
						<a type="button" class="close font-weight-bold" href="/program/delete/<?= $id ?>">×</a>
						<p class="card-text m-0"><?= $this->translate('Education Level'); ?>: <span class="font-weight-bold"><?= $program->getAttribute('level_title'); ?></span></p>
						<p class="card-text m-0"><?= $this->translate('Education Form'); ?>: <span class="font-weight-bold"><?= $program->getAttribute('form_title'); ?></span></p>
						<p class="card-text m-0"><?= $this->translate('Education Period'); ?>: <span class="font-weight-bold"><?= $program->getAttribute('period'); ?> <?= $this->translate('year(s)'); ?></span></p>
					</div>
			</div>					
		<?php endforeach; ?>
		</div>		
	<?php endforeach; ?>
	</div>	
<?php endforeach; ?>
</div>		
	<div class="w-100"></div>
	<button type="button" class="btn btn-primary ml-auto mr-5 px-3 d-flex" data-toggle="modal" data-target="#addProgram"><?= $this->translate('Add Program'); ?></button>
	</div>
	
<?php endif; ?>
<?= $this->form()->openTag($schoolForm); ?>
<?= $this->formHidden($schoolForm->get('id'));?>
<?php foreach($inputs as $input) : ?>
<div class="form-group">
    <?= $this->formLabel($input) ?>
    <?php if($input->getAttribute('type') != 'checkbox') : ?>
    <?= $this->formElement($input->setAttribute('class', 'form-control')) ?>
    <?php else : ?>
    <?= $this->formElement($input->setAttribute('class', 'form-check')) ?>
    <?php endif; ?>
    <?= $this->formElementErrors()->render($input, ['class' => 'help-block']) ?>
</div>
<?php endforeach; ?>
<?= $this->formSubmit($schoolForm->get('submit')->setAttribute('class', 'btn btn-primary mt-3 mb-5'));?>
<?= $this->form()->closeTag(); ?>
<p>&nbsp;</p>
<?php
$programForm = $this->programForm;
$programForm->setAttribute('action', $this->url('program', ['action' => 'add', 'id' => $this->id]))->setAttribute('id', 'program');
$id_school = $programForm->get('id_school')->setValue($this->id);
$program = $programForm->get('title')->setLabel('Education Program')->setAttribute('class', 'form-control');
$period = $programForm->get('period')->setLabel('Learning Period')->setAttributes(['class' => 'form-control', 'placeholder' => '4.5']);
$year = $programForm->get('year')->setLabel('Year')->setAttributes(['class' => 'form-control', 'placeholder' => date('Y')]);
$specialty = $programForm->get('id_specialty')->setLabel('Specialty')->setAttribute('class', 'form-control');
$level = $programForm->get('id_level')->setLabel('Select Level')->setAttribute('class', 'form-control');
$form = $programForm->get('id_form')->setLabel('Education Form')->setAttribute('class', 'form-control');
$programForm->prepare();
?>
<div class="modal fade" id="addProgram" tabindex="-1" role="dialog" aria-labelledby="addProgramLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="addProgramLabel"><?= $this->translate('Add Program'); ?></h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="<?= $this->translate('Close'); ?>">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<?= $this->form()->openTag($programForm); ?>
					<?= $this->formHidden($id_school);?>
					<div class="form-group">
					<?= $this->formLabel($program) ?>
					<?= $this->formElement($program); ?>
					</div>
					<div class="form-group">
					<?= $this->formLabel($specialty) ?>
					<?= $this->formElement($specialty); ?>
					</div>
					<div class="form-group">
					<?= $this->formLabel($level) ?>
					<?= $this->formElement($level); ?>
					</div>
					<div class="form-group">
					<?= $this->formLabel($form) ?>
					<?= $this->formElement($form) ?>
					</div>
					<div class="form-group">
					<?= $this->formLabel($period) ?>
					<?= $this->formElement($period); ?>
					</div>
				<?= $this->form()->closeTag(); ?>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal"><?= $this->translate('Back'); ?></button>
				<button form="program" type="submit" class="btn btn-primary"><?= $this->translate('Save'); ?></button>
			</div>
		</div>
	</div>
</div>