<?php
$paginator = $this->paginator;
if($this->high) :
    $title = $this->translate('Kharkov universities');
    $this->headTitle($title);
else :
    $title = $this->translate('Kharkov schools');
    $this->headTitle($title); ?>
<?= $this->headLink()->prependStylesheet($this->basePath() . 'https://use.fontawesome.com/releases/v5.7.2/css/all.css'); ?>
    <form method="post">
        <label class="small">
        <span>Показать район</span>
        <select name="area" id="area" onChange="this.form.submit();">
        <option value="0">Все</option>
    <?php
    foreach($areas as $indx => $areaName) :
        $selected = ($this->area == ($indx+1)) ? 'selected="selected"' : '';       
        ?>
        <option value="<?= ($indx+1);?>" <?= $selected;?>><?= $areaName;?></option>
    <?php endforeach; ?>
        </select>
        </label>
    </form>
<?php endif; ?>
<h1><?= $title;?></h1>
<table class="table table-striped">
    <tbody>
<?php foreach ($paginator as $item): ?>        
        <tr>
            <td class="col-md-1"><?= $item->id;?></td>
            <td class="col-md-auto">
                <a href="<?= $this->url('schools', array('action'=>'view', 'id' => $item->id, 'area' => null)); ?>"><?= $item->name;?></a>
            </td>
            <td class="col-md-2">
                <a class="fa fa-edit pr-3" title="Редактировать" href="/admin/edit/<?= $item->id;?>"></a>
                <a class="fa fa-trash-alt" title="Удалить" href="/admin/delete/<?= $item->id;?>"></a>
            </td>
        </tr>            
<?php endforeach;?>
    </tbody>
</table>


<?= $this->paginationControl($paginator,
     'Sliding',
     'application/index/page.phtml', [
         'high' => $this->high,
         'area' => $this->area
     ]);
if(isset($username)) : ?>
<br /><a class="btn btn-primary my-3" href="/admin/add/<?= $this->high; ?>">Добавить</a>
<?php endif; ?>
