<?php
$paginator = $this->paginator;
echo $this->headLink()->prependStylesheet($this->basePath() . 'https://use.fontawesome.com/releases/v5.7.2/css/all.css');
echo $this->inlineScript()->appendFile('/js/load_json.js');
if($this->high) :
    $title = $this->translate('Kharkov universities');
    $this->headTitle($title);
else :
    $title = $this->translate('Kharkov schools');
    $this->headTitle($title); ?>
<div class="d-inline-flex form-group mt-3 small">
    <form method="post">
        <label for="area"><?= $this->translate('Select Area'); ?></label>
        <select class="custom-select custom-select-sm" name="area" id="area" onChange="this.form.submit();">
            <option value="0"><?= $this->translate('All'); ?></option>
    <?php
    foreach($areas as $indx => $areaName) :
        $selected = ($this->area == ($indx+1)) ? 'selected="selected"' : '';       
    ?>
            <option value="<?= ($indx+1);?>" <?= $selected;?>><?= $areaName;?></option>
    <?php endforeach; ?>
        </select>
    </form>        
</div>
<?php endif; ?>
<h1 class="text-center"><?= $title;?></h1>
<?php if($this->high) : ?>
<div class="row">
    <div class="col">
        <a class="btn btn-primary my-3" id="import" href="/import"><?= $this->translate('Import Page'); ?></a>
    </div>
</div>
<div class="d-inline-flex form-group mt-3 small">
    <form>
        <label for="area"><?= $this->translate('Select Region'); ?></label>
        <select class="custom-select custom-select-sm" name="region" id="region" onchange="this.form.submit();">
			<option value="0"><?= $this->translate('All'); ?></option>
<?php
foreach($this->regions as $region) :
	$selected = ($region->id == $this->id_region) ? 'selected="selected"' : '';    
?>
            <option <?= $selected; ?> value="<?= $region->id; ?>"><?= $region->title; ?></option>
<?php endforeach; ?>
        </select>
    </form>
	<span id="sort-field" class="d-none"><?= $this->field; ?></span>
	<span id="sort-order" class="d-none"><?= $this->order; ?></span>
</div>
<?php endif; ?>
<?= $this->paginationControl($paginator,
     'Sliding',
     'application/index/page.phtml', [
         'high' => $this->high,
         'area' => $this->area,
		 'id_region' => $this->id_region,
     ]); ?>
<div class="table-responsive">
<table class="table table-striped">
	<thead class="thead-dark">
		<tr>
			<th id="th-id">ID</th>
			<th id="th-name_uk"><?= $this->translate('Name'); ?></th>
			<th id="th-id_edbo"><?= $this->translate('ID EDBO'); ?></th>
			<th><?= $this->translate('Edit schools'); ?></th>
		</tr>
	</thead>
    <tbody>
<?php
		foreach ($paginator as $item):
			$hasJson = $this->hasJsonOffersFile[$item->id];
?>
        <tr>
            <td class="id_school"><?= $item->id;?></td>
            <td>
                <a class="school" href="<?= $this->url('schools', array('action'=>'view', 'id' => $item->id, 'area' => null)); ?>"><?= $item->{'name_'.$this->plugin('translate')->getTranslator()->getLocale()};?></a>
            </td>
			<td class="id_edbo"><?= $item->id_edbo;?></td>
            <td>
				<span class="id_region d-none"><?= $item->id_region;?></span>
				<a class="fas fa-cloud-download-alt pr-3 download" title="<?= $this->translate('Get EDBO JSON file'); ?>" href="#"></a>
				<a class="fas fa-sync pr-3 update <?= $hasJson ? 'text-primary' : 'text-secondary disabled' ?>" title="<?= $hasJson ? $this->translate('Read data from JSON file') : $this->translate('Download JSON file first') ?>" href="#" disabled></a>
                <a class="fa fa-edit pr-3" title="<?= $this->translate('Edit'); ?>" href="/admin/edit/<?= $item->id;?>"></a>
                <a class="fa fa-trash-alt" title="<?= $this->translate('Delete'); ?>" href="/admin/delete/<?= $item->id;?>"></a>
            </td>
        </tr>            
<?php endforeach;?>
    </tbody>
</table>
</div>

<?= $this->paginationControl($paginator,
     'Sliding',
     'application/index/page.phtml', [
         'high' => $this->high,
         'area' => $this->area,
		 'id_region' => $this->id_region,
     ]);
if(isset($username)) : ?>
<br /><a class="btn btn-primary mt-0 mb-5" href="/admin/add/<?= $this->high; ?>"><?= $this->translate('Add school'); ?></a>
<?php endif; ?>
