<?php
$paginator = $this->paginator;
echo $this->headLink()->prependStylesheet($this->basePath() . 'https://use.fontawesome.com/releases/v5.7.2/css/all.css');
//$this->headScript()->appendFile('/js/ajax.js', 'text/javascript', []);
echo $this->inlineScript()->appendFile('/js/load_json.js');
if($this->high) :
    $title = $this->translate('Kharkov universities');
    $this->headTitle($title);
else :
    $title = $this->translate('Kharkov schools');
    $this->headTitle($title); ?>
<div class="d-inline-flex form-group mt-3 small">
    <form method="post">
        <label for="area"><?= $this->translate('Select Area'); ?></label>
        <select class="custom-select custom-select-sm" name="area" id="area" onChange="this.form.submit();">
            <option value="0"><?= $this->translate('All'); ?></option>
    <?php
    foreach($areas as $indx => $areaName) :
        $selected = ($this->area == ($indx+1)) ? 'selected="selected"' : '';       
    ?>
            <option value="<?= ($indx+1);?>" <?= $selected;?>><?= $areaName;?></option>
    <?php endforeach; ?>
        </select>
    </form>        
</div>
<?php endif; ?>
<h1 class="text-center"><?= $title;?></h1>
<div class="row">
    <div class="col">
        <a class="btn btn-primary" id="import" href="/import">Import Page</a>
    </div>
</div>
<?= $this->paginationControl($paginator,
     'Sliding',
     'application/index/page.phtml', [
         'high' => $this->high,
         'area' => $this->area
     ]); ?>
<div class="table-responsive">
<table class="table table-striped">
	<thead>
		<tr>
			<th>ID</th>
			<th><?= $this->translate('Name'); ?></th>
			<th><?= $this->translate('ID EDBO'); ?></th>
			<th><?= $this->translate('Edit schools'); ?></th>
		</tr>
	</thead>
    <tbody>
<?php foreach ($paginator as $item): ?>        
        <tr>
            <td class="id_school"><?= $item->id;?></td>
            <td>
                <a class="school" href="<?= $this->url('schools', array('action'=>'view', 'id' => $item->id, 'area' => null)); ?>"><?= $item->{'name_'.$this->plugin('translate')->getTranslator()->getLocale()};?></a>
            </td>
			<td class="id_edbo"><?= $item->id_edbo;?></td>
            <td>
				<a class="fas fa-sync pr-3 update" title="Sycnchronize with EDBO" href="#"></a>
                <a class="fa fa-edit pr-3" title="Edit" href="/admin/edit/<?= $item->id;?>"></a>
                <a class="fa fa-trash-alt" title="Delete" href="/admin/delete/<?= $item->id;?>"></a>
            </td>
        </tr>            
<?php endforeach;?>
    </tbody>
</table>
</div>

<?= $this->paginationControl($paginator,
     'Sliding',
     'application/index/page.phtml', [
         'high' => $this->high,
         'area' => $this->area
     ]);
if(isset($username)) : ?>
<br /><a class="btn btn-primary mt-0 mb-5" href="/admin/add/<?= $this->high; ?>"><?= $this->translate('Add school'); ?></a>
<?php endif; ?>
