<?php if ($this->pageCount): ?>
<div class="pagination mb-5">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
<li class="page-item">
  <a class="page-link" href="<?= $this->url('admin', array(
      'action' => 'index',
      'id' => $this->high,
      'area' => $this->area,
      'page' => $this->previous
  )); ?>">Prev</a>
</li>
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page):
    ($page == $this->current) ? $active = ' active' : $active = '' ?>
<li class="page-item<?= $active; ?>">
    <a class="page-link" href="<?= $this->url('admin', array(
        'action' => 'index',
        'id' => $this->high,
        'area' => $this->area,
        'page' => $page,
    )); ?>"><?= $page; ?></a>
</li>    
<?php endforeach; ?>
    
<!-- Next page link -->
<?php if (isset($this->next)): ?>
<li class="page-item">
  <a class="page-link" href="<?= $this->url('admin', array(
      'action'=> 'index',
      'id'=> $this->high,
      'area'=> $this->area,
      'page' => $this->next
  )); ?>">Next</a>
</li>
<?php endif; ?>
</div>
<?php endif; ?>
