<?php

$title = $this->translate('Edit Program');
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath() . 'https://use.fontawesome.com/releases/v5.7.2/css/all.css');
$programForm = $this->programForm;
$programForm->setAttribute('action', $this->url('program', ['action' => 'edit', 'id' => $this->id]))->setAttribute('id', 'program');
$id = $programForm->get('id');
$id_school = $programForm->get('id_school');
$program = $programForm->get('title')->setLabel('Education Program')->setAttribute('class', 'form-control');
$period = $programForm->get('period')->setLabel('Learning Period')->setAttributes(['class' => 'form-control', 'placeholder' => '4.5']);
$year = $programForm->get('year')->setLabel('Year')->setAttributes(['class' => 'form-control', 'placeholder' => date('Y')]);
$specialty = $programForm->get('id_specialty')->setLabel('Specialty')->setAttribute('class', 'form-control');
$level = $programForm->get('id_level')->setLabel('Select Level')->setAttribute('class', 'form-control');
$form = $programForm->get('id_form')->setLabel('Education Form')->setAttribute('class', 'form-control');
$programForm->prepare();
?>
<div class="content pb-3">
	<h1 class="text-center"><?= $this->escapeHtml($title); ?></h1>
	<div class="row justify-content-center">
		<div class="col-10">
			<?= $this->form()->openTag($programForm); ?>
				<?= $this->formHidden($id);?>
				<?= $this->formHidden($id_school);?>
				<div class="form-group">
				<?= $this->formLabel($program) ?>
				<?= $this->formElement($program); ?>
				</div>
				<div class="form-group">
				<?= $this->formLabel($period) ?>
				<?= $this->formElement($period); ?>
				</div>
				<div class="form-group">
				<?= $this->formLabel($year) ?>
				<?= $this->formElement($year); ?>
				</div>
				<div class="form-group">
				<?= $this->formLabel($specialty) ?>
				<?= $this->formElement($specialty); ?>
				</div>
				<div class="form-group">
				<?= $this->formLabel($level) ?>
				<?= $this->formElement($level); ?>
				</div>
				<div class="form-group">
				<?= $this->formLabel($form) ?>
				<?= $this->formElement($form) ?>
				</div>
				<button class="btn btn-info mt-3 mb-5 mr-3" onclick="window.history.back();">&laquo; <?= $this->translate('Back'); ?></button>			
				<?= $this->formSubmit($programForm->get('submit')->setAttribute('class', 'btn btn-primary mt-3 mb-5'));?>
			<?= $this->form()->closeTag(); ?>
		</div>
	</div>
<?php if($this->subjects) : ?>
	<h3 class="text-center"><?= $this->translate('Subjects'); ?></h3>
	<div class="row justify-content-center">
		<div class="col-10">
			<form method="post" id="subjects" action="/subject/edit/<?= $this->id; ?>">
				<input type="hidden" name="id_program" id="id_program" value="<?= $this->id; ?>" />
	<?php foreach($this->subjects as $id => $subject) : ?>				
				<div class="form-row form-inline my-2">
					<input type="hidden" name="id[<?= $id; ?>]" id="subject[<?= $id; ?>]" value="<?= $subject['id']; ?>" />
					<input type="hidden" name="id_subject[<?= $id; ?>]" id="subject[<?= $id; ?>]" value="<?= $id; ?>" />
					<div class="form-group col-md-4">
						<input type="text" class="form-control w-100" name="title[<?= $id; ?>]" id="title[<?= $id; ?>]" value="<?= $subject['title']; ?>" readonly="readonly">
					</div>
					<div class="col-md-1">
						<a class="fa fa-trash-alt" title="Delete" href="#"> </a>
					</div>						
					<div class="form-group col-md-1 custom-control custom-switch">
						<input type="checkbox" class="custom-control-input" name="required[<?= $id; ?>]" id="required[<?= $id; ?>]" <?= ($subject['required']) ? 'checked' : 'unchecked'; ?>/>
						<label class="custom-control-label" for="required[<?= $id; ?>]"><?= $this->translate('Required'); ?></label>						    
					</div>
					<div class="form-group col-md-3">
						<label class="mr-2" for="coefficient[<?= $id; ?>]"><?= $this->translate('Coefficient'); ?></label> 
						<input type="text" class="form-control" name="coefficient[<?= $id; ?>]" id="coefficient[<?= $id; ?>]" value="<?= $subject['coefficient']; ?>">
					</div>
					<div class="form-group col-md-3">
						<label class="mr-2" for="rating[<?= $id; ?>]"><?= $this->translate('Rating'); ?></label> 
						<input type="number" min="100" max="200" class="form-control" name="rating[<?= $id; ?>]" id="rating[<?= $id; ?>]" value="<?= $subject['rating']; ?>">
					</div>
				</div>
<?php endforeach; ?>
			<button type="submit" class="btn btn-primary mt-2 mb-3"><?= $this->translate('Save'); ?></button>
			</form>				
		</div>
	</div>
<?php endif; ?>	
</div>
<p>&nbsp;</p>
