<?php

$title = 'Delete Subject';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete this Subject?</p>

<form action="<?= $this->url('subject', ['action' => 'delete', 'id' => $this->id_program]); ?>" method="post" id="subject">
<div class="form-group">
    <input type="hidden" id="id" name="id" value="<?= (int) $this->id; ?>" />
    <input class="btn btn-danger my-3 mr-1" type="submit" name="del" value="Yes" />
    <input class="btn btn-secondary" type="submit" name="del" value="Нет" />
</div>
</form>
