<?php   
$paginator = $this->paginator;
if($this->high) {
    $title = $this->translate('Kharkov universities');
    $this->headTitle($title);
}
else {
    $title = $this->translate('Kharkov schools');
    $this->headTitle($title);
} ?>
<h1><?= $title;?></h1>
<div class="row">
    <div class="col-md-8">
<?php if(!$this->high) :?>
<div class="d-inline-flex form-group mt-3 small">
    <form method="post">
        <label for="area">Показать район</label>
        <select class="custom-select custom-select-sm" name="area" id="area" onChange="this.form.submit();">
        <option value="0">Все</option>
    <?php
    foreach($areas as $indx => $areaName) :
        $selected = ($this->area == ($indx+1)) ? ' selected="selected"' : '';       
        ?>
        <option value="<?= ($indx+1);?>"<?= $selected;?>><?= $areaName;?></option>
    <?php endforeach; ?>
        </select>
    </form>
</div>
<?php endif; ?>
        <div class="card-columns">
        <?php foreach ($paginator as $item): ?>
            <div class="card">
                <div class="card-body">                
                <?php if($item->logo) : ?>
                <img class="card-img-top w-25" src="<?= $item->logo ?>" alt="logo" />
                <?php endif; ?>
                    <a class="align-bottom" href="<?= $this->url($this->route, array('action'=>'view', 'id'=>$item->id)); ?>"><?= $item->name;?></a>
                </div>
            </div>
        <?php endforeach;?>
        </div>
<?= $this->paginationControl($paginator,
     'Sliding',
     'application/index/page.phtml', [
         'high' => $this->high,
         'area' => $this->area
     ]); ?>
    </div>    
    <div class="col-md-1"></div>
    <div class="col-md-3">
      <h3>News</h3>  
<?php
$i = $news_max;
foreach ($news->channel['items'] as $item) :
    if($i>0) :
?>
<article class="card border-light rounded small my-2 p-2">
    <a class="h6" target="_blank" href="<?= $item['link']; ?>"><?= $item['title']; ?></a>    
<?php if ($item['enclosure']) : ?>
    <p class="mt-2"><img class="w-75" src="<?= $item['enclosure']->url; ?>" alt="<?= $item['title']; ?>" /></p>
<?php endif; ?>
    <p class="mb-1"><?= $item['description']; ?></p>
    <p>
    <?= $this->translate('Published'); ?>: <?= $this->dateFormat(
            new DateTime($item['pubDate']['date']),
                IntlDateFormatter::MEDIUM,
                IntlDateFormatter::MEDIUM,
                Locale::getDefault()); ?> 
    <a target="_blank" href="<?= $item['link']; ?>"><?= $this->translate('Details'); ?></a></p> 
</article>
    <?php endif;
    $i--;
endforeach; ?>
<h6><a target="_blank" href="<?= $news->channel['link']; ?>"><?= $news->channel['title']; ?></a></h6>
    </div>
</div>