<?php   
$paginator = $this->paginator;
if($this->high) {
    $title = $this->translate('Ukraine universities');
    $this->headTitle($title);
}
else {
    $title = $this->translate('Kharkov schools');
    $this->headTitle($title);
} ?>
<h1 class="text-center mt-3"><?= $title;?></h1>
<div class="row">
    <div class="col-md-8">
<?php if($this->high) :?>
<div class="d-inline-flex form-group mt-3 small">
    <form>
	<input type="hidden" name="type" value="<?= $this->type; ?>" />
        <label for="region"><?= $this->translate('Select Region'); ?></label>
        <select class="custom-select custom-select-sm" name="region" id="region" onchange="this.form.submit();">
			<option value="0"><?= $this->translate('All'); ?></option>
<?php
foreach($this->regions as $region) :
	$selected = ($region->id == $this->id_region) ? 'selected="selected"' : '';    
?>
            <option <?= $selected; ?> value="<?= $region->id; ?>"><?= $region->title; ?></option>
<?php endforeach; ?>
        </select>
    </form>
	<span id="sort-field" class="d-none"><?= $this->field; ?></span>
	<span id="sort-order" class="d-none"><?= $this->order; ?></span>
</div>
<div class="d-inline-flex form-group mt-3 small">
    <form>
		<input type="hidden" name="region" value="<?= $this->id_region; ?>" />
        <label for="type"><?= $this->translate('Select Type'); ?></label>
        <select class="custom-select custom-select-sm" name="type" id="type" onchange="this.form.submit();">
<?php
foreach($this->types as $key => $item) :
	if(!$item) {
		$item = $this->translate('All');
	}
	$selected = ($key == $this->type) ? 'selected="selected"' : '';    
?>
            <option <?= $selected; ?> value="<?= $key; ?>"><?= $item; ?></option>
<?php endforeach; ?>
        </select>
    </form>
</div>
<?php else: ?>
<div class="d-inline-flex form-group mt-3 small">
    <form method="post">
        <label for="area"><?= $this->translate('Select Area'); ?></label>
        <select class="custom-select custom-select-sm" name="area" id="area" onChange="this.form.submit();">
        <option value="0"><?= $this->translate('All'); ?></option>
    <?php
    foreach($areas as $indx => $areaName) :
        $selected = ($this->area == ($indx+1)) ? ' selected="selected"' : '';       
        ?>
        <option value="<?= ($indx+1);?>"<?= $selected;?>><?= $areaName;?></option>
    <?php endforeach; ?>
        </select>
    </form>
</div>
<?php endif; ?>
<?= $this->paginationControl($paginator,
     'Sliding',
     'application/index/page.phtml', [
         'high' => $this->high,
         'area' => $this->area,
		 'id_region' => $this->id_region,
		 'type' => $this->type,
     ]); ?>
        <div class="card-columns">
        <?php foreach ($paginator as $item): ?>
            <div class="card">
                <div class="card-body w-100 pt-0">
                <?php if($item->shortname) : ?>
                    <a class="align-bottom" href="<?= $this->url($this->route, array('action'=>'view', 'id'=>$item->id)); ?>"><h5><span class="badge badge-pill w-25 btn btn-outline-primary float-right text-truncate px-3 mr-0" title="<?= $item->shortname ?>"><?= $item->shortname ?></span></h5></a>
                <?php endif;
                if($item->logo) : ?>
                    <a class="align-bottom" href="<?= $this->url($this->route, array('action'=>'view', 'id'=>$item->id)); ?>"><img class="card-img-top w-25" src="<?= $item->logo ?>" alt="logo" /></a>
                <?php endif; ?>
                    <a class="align-bottom" href="<?= $this->url($this->route, array('action'=>'view', 'id'=>$item->id)); ?>"><?= $item->{'name_'.$this->plugin('translate')->getTranslator()->getLocale()};?></a>
                </div>
            </div>
        <?php endforeach;?>
        </div>
<?= $this->paginationControl($paginator,
     'Sliding',
     'application/index/page.phtml', [
         'high' => $this->high,
         'area' => $this->area,
		 'id_region' => $this->id_region,
		 'type' => $this->type,
     ]); ?>
    </div>    
    <div class="col-md-1"></div>
    <div class="col-md-3">
      <h3><?= $this->translate('News'); ?></h3>  
<?php
$i = $news_max;
foreach ($news->channel['items'] as $item) :
    if($i>0) :
?>
<div class="card border-light rounded small my-2 p-2">
    <a class="h6" target="_blank" href="<?= $item['link']; ?>"><?= $item['title']; ?></a>    
<?php if ($item['enclosure']) : ?>
    <p class="mt-2"><img class="w-75" src="<?= $item['enclosure']->url; ?>" alt="<?= $item['title']; ?>" /></p>
<?php endif; ?>
    <p class="mb-1"><?= $item['description']; ?></p>
    <p>
    <?= $this->translate('Published'); ?>: <?= $this->dateFormat(
            new DateTime($item['pubDate']['date']),
                IntlDateFormatter::MEDIUM,
                IntlDateFormatter::MEDIUM,
                Locale::getDefault()); ?> 
    <a target="_blank" href="<?= $item['link']; ?>"><?= $this->translate('Details'); ?></a></p> 
</div>
    <?php endif;
    $i--;
endforeach; ?>
<h6><a target="_blank" href="<?= $news->channel['link']; ?>"><?= $news->channel['title']; ?></a></h6>
    </div>
</div>
