<?php
use Zend\Authentication\Storage\Session as SessionStorage;

$form = $this->form;
$form->setAttribute('action', $this->url(
    'index',
    array(
        'action' => 'login',
    )
))->setAttribute('class', 'w-50 mt-5');

$login = $form->get('login');
$login->setAttribute('class', 'form-control');
$login->setAttribute('placeholder', 'Login');

$passwd = $form->get('passwd');
$passwd->setAttribute('class', 'form-control');
$passwd->setAttribute('placeholder', 'Password');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary my-3')->setAttribute('value', 'Ok');

$form->prepare();
?>
<div class="row align-items-center h-100">
    <div class="col-md-3"></div>
    <div class="col-md-9">
    <?= $this->form()->openTag($form); ?>

                    <div class="form-group">
                        <?= $this->formLabel($login) ?>
                        <?= $this->formElement($login) ?>
                        <?= $this->formElementErrors()->render($login, ['class' => 'help-block']) ?>
                        <?= $this->formLabel($passwd) ?>
                        <?= $this->formElement($passwd) ?>
                        <?= $this->formElementErrors()->render($passwd, ['class' => 'help-block']) ?>
                        <?= $this->formSubmit($submit); ?>
                    </div>
                <?= $this->form()->closeTag(); ?>
    </div>
</div>