<?php

if ($this->pageCount):
?>
<div class="pagination mb-5 justify-content-center">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
<li class="page-item">
  <a class="page-link" href="<?= $this->url($this->route, array(
      'action'=>'index',
      'id'=>$this->high,
      'area'=>$this->area,
      'page' => $this->previous
  )); ?>">&larr;Пред</a>
</li>
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page):
    ($page == $this->current) ? $active = ' active' : $active = '' ?>
<li class="page-item<?= $active; ?>">
    <a class="page-link" href="<?= $this->url($this->route, [
        'action'=>'index',
        'id'=>$this->high,
        'area'=>$this->area,
        'page' => $page,
    ]); ?>"><?= $page; ?></a>
</li>    
<?php endforeach; ?>
    
<!-- Next page link -->
<?php if (isset($this->next)): ?>
<li class="page-item">
  <a class="page-link" href="<?= $this->url($this->route, array(
      'action'=>'index',
      'id'=>$this->high,
      'area'=>$this->area,
      'page' => $this->next
  )); ?>">След&rarr;</a>
</li>
<?php endif; ?>
</div>
<?php endif; ?>
