<h1>Результаты поиска "<?= $search; ?>"</h1>
<h3>Найдено совпадений: <?= count($results); ?></h3>
<?php if(count($results)) : ?>
<table class="table table-striped">
    <tbody>
    <?php foreach ($results as $school): ?>        
        <tr>
            <td class="col-md-auto">
                <p><a href="<?= $this->url('schools', array('action'=>'view', 'id' => $school['id'], 'area' => null)); ?>"><?= $school['name'];?></a></p>
                <?php if(isset($school['found'])) : ?>
                    <?php foreach ($school['found'] as $item): ?>  
                <p class="small"><?= $item['value']; ?></p>
                    <?php endforeach; ?>
                <?php endif; ?>
            </td>
        </tr>            
    <?php endforeach; ?>
    </tbody>
</table>
<br />
<?php endif; ?>
