<?php
echo $this->headScript()->appendFile('/js/smile.js');
$title = $school->shortname;
$this->headTitle($title);
if($this->api) :
?>
<textarea class="w-100 mt-5 p-3" rows="24">
<?= $this->api == 'json' ? Zend\Json\Json::prettyPrint(Zend\Json\Json::fromXml($this->specialtyDOM->saveXML(), false)) : $this->specialtyDOM->saveXML(); ?>
</textarea>
<?php else : ?>
<table class="table table-striped">
    <tbody>
        <tr>
            <td class="align-middle">
                <h4><?php if($school->logo) : ?>
                <img style="max-width: 100px;" src="<?= $school->logo; ?>" alt="logo" />
                <?php endif; ?>
                <?= $school->{'name_'.$this->plugin('translate')->getTranslator()->getLocale()}; ?></h4>
            </td>	
        </tr>
		<?php if($school->high && isset($this->specialties)) : ?>
		<tr>
            <td class="px-0">		    
                <h4 class="m-3"><?= $this->translate('Specialties'); ?></h4>
			<?php
			$branches = $this->specialtyDOM->getElementsByTagName('branch');
			foreach($branches as $branch) :
			?>
				<h5 class="m-3"><?= $this->translate('Branch Title'); ?>: <?= $branch->getAttribute('code'); ?> <?= $branch->firstChild->textContent; ?></h5>
			<?php
				$specialties = $branch->getElementsByTagName('specialty');
				foreach($specialties as $specialty) :
			?>
			    <div class="accordion" id="specialities">
					<div class="card mt-2">
						<div class="card-header" id="<?= $specialty->getAttribute('id') ?>">
							<h4 class="mb-0">
								<button class="btn btn-link p-0 text-decoration-none" role="button" type="button" data-toggle="collapse" data-target="#collapse_<?= $specialty->getAttribute('id') ?>" aria-expanded="false" aria-controls="collapse_<?= $specialty->getAttribute('id') ?>">
									<?= $this->translate('Specialty Title'); ?>: <?= $specialty->getAttribute('code'); ?> <?= $specialty->firstChild->textContent; ?>
								</button>
							</h4>
						</div>

						<div id="collapse_<?= $specialty->getAttribute('id') ?>" class="collapse p-1" aria-labelledby="<?= $specialty->getAttribute('id') ?>" data-parent="#specialities">
							<div class="card-columns">
				<?php
					$programs = $specialty->getElementsByTagName('program');
					foreach($programs as $program) :
						$subjects = $program->getElementsByTagName('subject');
				?>

								<div class="card border border-primary p-0">
									<div class="card-header text-white bg-primary">
										<h6 class="card-title"><span class=" font-weight-bold"><?= $this->translate('Education Program'); ?>: </span><?= $program->firstChild->textContent; ?></h6>
									</div>
									<div class="card-body p-0">
										<div class="card-text px-2">
											<p>
												<span class=" font-weight-bold"><?= $this->translate('Education Level'); ?>: </span><?= $program->getAttribute('level_title'); ?><br/>
												<span class=" font-weight-bold"><?= $this->translate('Education Form'); ?>: </span><?= $program->getAttribute('form_title'); ?><br/>
												<span class=" font-weight-bold"><?= $this->translate('Education Period'); ?>: </span><?= $program->getAttribute('period'); ?><br/>
												<span class=" font-weight-bold"><?= $this->translate('Competition scores'); ?>: </span><?= $this->translate('min'); ?>&nbsp;=&nbsp;<?= $program->getAttribute('min_rate'); ?>; <?= $this->translate('ave'); ?>&nbsp;=&nbsp;<?= $program->getAttribute('ave_rate'); ?>; <?= $this->translate('max'); ?>&nbsp;=&nbsp;<?= $program->getAttribute('max_rate'); ?>
											</p>
						<?php if($subjects) : ?>
											<p>
												<span class=" font-weight-bold"><?= $this->translate('Subjects'); ?>:</span><br/>

							<?php
							$i = 1;
							foreach($subjects as $subject) :
							?>
												<?= $subject->firstChild->textContent; ?>
												<span class=" font-weight-bold"><?= $subject->getAttribute('required') ? ' - ' . $this->translate('is required') : null ?></span>
												(<?= $this->translate('Subject Rating'); ?>&nbsp;=&nbsp;<?= $subject->getAttribute('rating'); ?>;
												K<?= $i; ?>&nbsp;=&nbsp;<?= rtrim($subject->getAttribute('coefficient'), '0'); ?>)<br/>
							<?php
							if($subject->getAttribute('required')) {
								$i++;
							}
							endforeach;
							?>
											</p>											
						<?php endif; ?>
										</div>
									</div>
									<div class="card-footer">
										<a href="#" class="card-link"><?= $this->translate('Details'); ?></a>
									</div>
								</div>	
				<?php
					endforeach;
				?>
							</div>							
						</div>
				    </div>
			    </div>
		<?php
			    endforeach;
		    endforeach;
		?>
			</td>
        </tr>
		<?php endif; ?>
        <tr>
            <td>
                <span class="font-weight-bold"><?= $this->translate('Address'); ?>: </span>
                <?= $school->address; ?>
            </td>	
        </tr>
        <tr>	
            <td>
                <span class="font-weight-bold"><?= $this->translate('Phone'); ?>: </span>
            <?= $school->phone; ?>
            </td>
        </tr>	
        <tr>		
            <td>
                <span class="font-weight-bold">E-mail: </span>
                <a target="_blank" href="mailto://<?= $school->email;?>"><?= $school->email;?></a>
            </td>
        </tr>	
        <tr>		
            <td>
                <span class="font-weight-bold">WWW: </span>
                <a target="_blank" href="<?= $school->http;?>"><?= parse_url($school->http, PHP_URL_HOST);?></a>
            </td>	
        </tr>
<?php if($school->info) : ?>
        <tr>	
            <td>
                <span class="font-weight-bold"><?= $this->translate('Information'); ?>: </span>
                <?= $school->info; ?>
            </td>	
        </tr>
<?php endif; ?>
        <tr>	
            <td>
                <span class="font-weight-bold"><?= $this->translate('Area'); ?></span>
                <?= $school->area; ?>
            </td>
        </tr>	
        <tr>	
            <td>
                <span class="font-weight-bold"><?= $this->translate('Map'); ?></span>
                <?= $school->map; ?>
            </td>	
        </tr>
    </tbody>
</table>
<h3><?= $this->translate('User reviews'); ?></h3>
<div class="row"><!-- Existing comments -->
    <div class="col-md-12">
<?php
foreach ($comments as $comment) :
    $text = $comment->insertSmile();
    if(isset($username)) :
?>
        <div class="card border border-secondary my-3">
            <div class="card-header">
<?php
// Form for Comment Deletion
$form = $this->form;
$form->setAttribute('action', $this->url(
    'admin',
    [
        'action' => 'delcomment',
        'id'     => $comment->id,
        'area' => null,
        'page' => null,    
    ]))
    ->setAttribute('class', 'd-inline-flex')
    ->setAttribute('name', 'delcomment')
    ->setAttribute('id', 'delcomment')    ;

$form->bind($comment);
$form->get('id')->setValue($comment->id);
$form->prepare(); ?>
<?= $this->form()->openTag($form); ?>
<?= $this->formSubmit($form->get('delComment')
        ->setAttribute('class', 'btn btn-light font-weight-bold px-2 py-1')
        ->setAttribute('value', 'X')); ?>
<?= $this->form()->closeTag(); ?>
        
            
<?php
// Form for $comment->visible switch on/off
$form->setAttribute('action', $this->url(
    'schools',
    [
        'action' => 'view',
        'id'     => $school->id,
        'area' => null,
        'page' => null,  
    ]))
    ->setAttribute('class', 'd-inline-flex p-2 mr-3')
    ->setAttribute('name', 'disComment')
    ->setAttribute('id','disComment');
$form->get('visible')
    ->setAttribute('onchange', 'this.form.submit();')
    ->setAttribute('title', $this->translate('Visible to users'));
$form->bind($comment);
$form->get('id')->setValue($comment->id);
$form->prepare();
?>
<?= $this->form()->openTag($form); ?>
<?= $this->formHidden($form->get('id')); ?>
<?= $this->formCheckbox($form->get('visible')); ?>
<?= $this->form()->closeTag(); ?>
<?php $text = $comment->censorComment($text); ?>
<?= $comment->author;?> | <?= (strftime('%d %b %Y %X ',$comment->time));?>
            </div>
            <div class="card-body"><?= nl2br($text); ?></div>
        </div>
<?php
    else :
        if($comment->visible) :
            $text = $comment->censorComment($text);?>
        <div class="card border border-secondary my-3">
            <div class="card-header">
<?= $comment->author;?> | <?= (strftime('%d %b %Y %X ', $comment->time));?>
            </div>
            <div class="card-body"><?=  nl2br($text); ?></div>
        </div>
<?php
        endif;
    endif;
endforeach;   
?>
    </div>
</div><!-- Existing comments END -->
<div class="row bg-dark text-light py-5"><!-- New comment -->
    <div class="col-md-12">
        <h4><?= $this->translate('Add a review'); ?></h4>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'schools',
    array(
        'action' => 'view',
        'id'     => $school->id,
        'area' => null,
        'page' => null,  
    )
));
$form->setAttribute('class', 'd-block')
    ->setAttribute('name', 'comment')
    ->setAttribute('id', 'comment')
    ->prepare();
$form->get('id')->setValue(0);
$form->get('text')->setValue('');
?>
<?= $this->form()->openTag($form); ?>
        <div class="form-group">
<?= $this->formHidden($form->get('id')); ?>
<?php if(isset($username)) :
    $form->get('author')
        ->setValue($this->translate('Administrator'))
        ->setLabel($this->translate('User'));
endif; ?>
<?= $this->formRow($form->get('author')->setAttribute('class', 'form-control')); ?>
            <div class="nav bg-dark text-light border-0 nav-tabs"><div class="nav-link active py-0"><?php include($docRoot.'/smile.html'); ?></div></div>
<?= $this->formRow($form->get('text')->setAttribute('class', 'form-control p-2 mt-0 rounded-0')->setAttribute('style', 'height: 10rem;')); ?>
<br />
<?php $form->get('submit')
        ->setAttribute('title', $this->translate('Save'))
        ->setAttribute('id', 'submitbutton')
        ->setAttribute('class', 'btn btn-primary mb-3')
        ->setValue($this->translate('Save')); ?>
<?= $this->formSubmit($form->get('submit')); ?>
        </div>
<?= $this->form()->closeTag(); ?>
    </div>
</div><!-- New comment END -->
<?php endif; ?>