<?php
$title = $school->shortname;
$this->headTitle($title);
?>
<script src="/js/smile.js"></script>
<?php /*($this->headScript()->prependFile("/js/smile.js"));*/ ?>
<table class="table">
    <tbody>
        <tr>
            <th><?php if($school->logo) : ?><img style="max-width: 100px;" src="<?= $school->logo; ?>" alt="logo" /><?php endif; ?></th>
            <td class="align-middle"><h2><?= $school->{'name_'.$this->plugin('translate')->getTranslator()->getLocale()}; ?></h2></td>	
        </tr>
		<?php if($school->high && isset($this->specialties)) : ?>
		<tr>
            <th><?= $this->translate('Specialties'); ?></th>
            <td>
				<div class="accordion" id="specialities">				
			<?php
			$branches = $this->specialtyDOM->getElementsByTagName('branch');
			foreach($branches as $branch) :
			?>
				<h4><?= $this->translate('Branch Title'); ?>: <?= $branch->getAttribute('code'); ?> <?= $branch->firstChild->textContent; ?></h4>
			<?php
				$specialties = $branch->getElementsByTagName('specialty');
				foreach($specialties as $specialty) :
			?>				
					<div class="card">
						<div class="card-header" id="<?= $specialty->getAttribute('id') ?>">
							<h4 class="mb-0">
								<button class="btn btn-link p-0 text-decoration-none" role="button" type="button" data-toggle="collapse" data-target="#collapse_<?= $specialty->getAttribute('id') ?>" aria-expanded="false" aria-controls="collapse_<?= $specialty->getAttribute('id') ?>">
									<?= $this->translate('Specialty Title'); ?>: <?= $specialty->getAttribute('code'); ?> <?= $specialty->firstChild->textContent; ?>
								</button>
							</h4>
						</div>

						<div id="collapse_<?= $specialty->getAttribute('id') ?>" class="collapse" aria-labelledby="<?= $specialty->getAttribute('id') ?>" data-parent="#specialities">
							<div class="card-body">
				<?php
					$programs = $specialty->getElementsByTagName('program');
					foreach($programs as $program) :
				?>
								<div class="card-text">
									<h5><?= $this->translate('Education Program'); ?>: <?= $program->firstChild->textContent; ?></h5>
									<p><?= $this->translate('Education Level'); ?>: <?= $program->getAttribute('level_title'); ?></p>
									<p><?= $this->translate('Education Form'); ?>: <?= $program->getAttribute('form_title'); ?></p>
									<p><?= $this->translate('Education Period'); ?>: <?= $program->getAttribute('period'); ?> <?= $this->translate('year(s)'); ?></p>
									<hr/>
								</div>
				<?php
					endforeach;
				?>
							</div>
						</div>
					</div>
			<?php
				endforeach;
			endforeach;
			?>
				</div>
			</td>
        </tr>
		<?php endif; ?>
        <tr>
            <th><?= $this->translate('Address'); ?></th>
            <td><?= $school->address; ?></td>	
        </tr>
        <tr>	
            <th><?= $this->translate('Phone'); ?></th>
            <td><?= $school->phone; ?></td>
        </tr>	
        <tr>		
            <th>E-mail</th>	
            <td><a target="_blank" href="mailto://<?= $school->email;?>"><?= $school->email;?></a></td>
        </tr>	
        <tr>		
            <th>WWW</th>
            <td><a target="_blank" href="<?= $school->http;?>"><?= parse_url($school->http, PHP_URL_HOST);?></a></td>	
        </tr>
<?php if($school->info) : ?>
        <tr>	
            <th><?= $this->translate('Information'); ?></th>
            <td><?= $school->info; ?></td>	
        </tr>
<?php endif; ?>
        <tr>	
            <th><?= $this->translate('Area'); ?></th>
            <td><?= $school->area; ?></td>
        </tr>	
        <tr>	
            <th><?= $this->translate('Map'); ?></th>
            <td><?= $school->map; ?></td>	
        </tr>
    </tbody>
</table>
<h3><?= $this->translate('User reviews'); ?></h3>
<div class="row"><!-- Existing comments -->
    <div class="col-md-12">
<?php
foreach ($comments as $comment) :
    $text = $comment->insertSmile();
    if(isset($username)) :
?>
        <div class="card border border-secondary my-3">
            <div class="card-header">
<?php
// Form for Comment Deletion
$form = $this->form;
$form->setAttribute('action', $this->url(
    'admin',
    [
        'action' => 'delcomment',
        'id'     => $comment->id,
        'area' => null,
        'page' => null,    
    ]))
    ->setAttribute('class', 'd-inline-flex')
    ->setAttribute('name', 'delcomment')
    ->setAttribute('id', 'delcomment')    ;

$form->bind($comment);
$form->get('id')->setValue($comment->id);
$form->prepare(); ?>
<?= $this->form()->openTag($form); ?>
<?= $this->formSubmit($form->get('delComment')
        ->setAttribute('class', 'btn btn-light font-weight-bold px-2 py-1')
        ->setAttribute('value', 'X')); ?>
<?= $this->form()->closeTag(); ?>
        
            
<?php
// Form for $comment->visible switch on/off
$form->setAttribute('action', $this->url(
    'schools',
    [
        'action' => 'view',
        'id'     => $school->id,
        'area' => null,
        'page' => null,  
    ]))
    ->setAttribute('class', 'd-inline-flex p-2 mr-3')
    ->setAttribute('name', 'disComment')
    ->setAttribute('id','disComment');
$form->get('visible')
    ->setAttribute('onchange', 'this.form.submit();')
    ->setAttribute('title', $this->translate('Visible to users'));
$form->bind($comment);
$form->get('id')->setValue($comment->id);
$form->prepare();
?>
<?= $this->form()->openTag($form); ?>
<?= $this->formHidden($form->get('id')); ?>
<?= $this->formCheckbox($form->get('visible')); ?>
<?= $this->form()->closeTag(); ?>
<?php $text = $comment->censorComment($text); ?>
<?= $comment->author;?> | <?= (strftime('%d %b %Y %X ',$comment->time));?>
            </div>
            <div class="card-body"><?= nl2br($text); ?></div>
        </div>
<?php
    else :
        if($comment->visible) :
            $text = $comment->censorComment($text);?>
        <div class="card border border-secondary my-3">
            <div class="card-header">
<?= $comment->author;?> | <?= (strftime('%d %b %Y %X ', $comment->time));?>
            </div>
            <div class="card-body"><?=  nl2br($text); ?></div>
        </div>
<?php
        endif;
    endif;
endforeach;   
?>
    </div>
</div><!-- Existing comments END -->
<div class="row bg-dark text-light pt-5"><!-- New comment -->
    <div class="col-md-12">
        <h4><?= $this->translate('Add a review'); ?></h4>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'schools',
    array(
        'action' => 'view',
        'id'     => $school->id,
        'area' => null,
        'page' => null,  
    )
));
$form->setAttribute('class', 'd-block')
    ->setAttribute('name', 'comment')
    ->setAttribute('id', 'comment')
    ->prepare();
$form->get('id')->setValue(0);
$form->get('text')->setValue('');
?>
<?= $this->form()->openTag($form); ?>
        <div class="form-group">
<?= $this->formHidden($form->get('id')); ?>
<?php if(isset($username)) :
    $form->get('author')
        ->setValue($this->translate('Administrator'))
        ->setLabel($this->translate('User'));
endif; ?>
<?= $this->formRow($form->get('author')->setAttribute('class', 'form-control')); ?>
            <div class="nav bg-dark text-light border-0 nav-tabs"><div class="nav-link active py-0"><?php include($docRoot.'/smile.html'); ?></div></div>
<?= $this->formRow($form->get('text')->setAttribute('class', 'form-control p-2 mt-0 rounded-0')->setAttribute('style', 'height: 10rem;')); ?>
<br />
<?php $form->get('submit')
        ->setAttribute('title', $this->translate('Save'))
        ->setAttribute('id', 'submitbutton')
        ->setAttribute('class', 'btn btn-primary mb-3')
        ->setValue($this->translate('Save')); ?>
<?= $this->formSubmit($form->get('submit')); ?>
        </div>
<?= $this->form()->closeTag(); ?>
    </div>
</div><!-- New comment END -->
