<?php
echo $this->headLink()->prependStylesheet($this->basePath() . 'https://use.fontawesome.com/releases/v5.7.2/css/all.css');
$title = $school->name;
$this->headTitle($title);
?>
<?= ($this->headScript()->prependFile("/js/smile.js")); ?>
<h2 class="my-3"><?= $title; ?></h2>
<table class="table">
    <thead>
        <tr>
            <th>Адрес</th>
            <td><?= $school->address; ?></td>	
        </tr>
    </thead>
    <tbody>
        <tr>	
            <th>Телефон</th>
            <td><?= $school->phone; ?></td>
        </tr>	
        <tr>		
            <th>E-mail</th>	
            <td><a target="_blank" href="mailto://<?= $school->email;?>"><?= $school->email;?></a></td>
        </tr>	
        <tr>		
            <th>WWW</th>
            <td><a target="_blank" href="<?= $school->http;?>"><?= substr($school->http,7);?></a></td>	
        </tr>
<?php if($school->info) : ?>
        <tr>	
            <th>Информация</th>
            <td><?= $school->info; ?></td>	
        </tr>
<?php endif; ?>
        <tr>	
            <th>Район</th>
            <td><?= $school->area; ?></td>
        </tr>	
        <tr>	
            <th>Карта</th>
            <td><?= $school->map; ?></td>	
        </tr>
    </tbody>
</table>
<h3>Отзывы пользователей</h3>
<ul class="simple">
<?php
foreach ($comments as $comment) :
    $text = $comment->insertSmile();
    if(isset($username)) :
?>
<li><div class="comment_header">
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'admin',
    array(
        'action' => 'delcomment',
        'id'     => $comment->id,
        'area' => null,
        'page' => null,      
    )
));

$form->bind($comment);
$form->get('id')->setValue($comment->id);
$form->prepare(); ?>
<?= $this->form()->openTag($form); ?>
<?= $this->formSubmit($form->get('delComment')); ?>
<?= $this->form()->closeTag(); ?>
        
            
<?php
// form $comment->visible on/off
$form->setAttribute('action', $this->url(
    'schools',
    array(
        'action' => 'view',
        'id'     => $school->id,
        'area' => null,
        'page' => null,  
    )
));
$form->setAttribute('name', 'disComment');
$form->setAttribute('id','disComment');
$form->get('visible')->setAttribute('class', 'commentCheckbox')
    ->setAttribute('onchange', 'this.form.submit();')
    ->setAttribute('title', 'Виден пользователям');
$form->bind($comment);
$form->get('id')->setValue($comment->id);
$form->prepare();
?>
<?= $this->form()->openTag($form); ?>
<?= $this->formHidden($form->get('id')); ?>
<?= $this->formCheckbox($form->get('visible')); ?>
<?= $this->form()->closeTag(); ?>
<?php $text = $comment->censorComment($text); ?>
<?= $comment->author;?> | <?= (strftime('%d %b %Y %X ',$comment->time));?>
</div><div class="comment">
    <?= $text; ?>
</div></li>
<?php
    else :
        if($comment->visible) :
            $text = $comment->censorComment($text);?>
<li><div class="comment_header">
<?= $comment->author;?> | <?= (strftime('%d %b %Y %X ',$comment->time));?>
</div><div class="comment"><?=  $text; ?></div></li>
<?php
        endif;
    endif;
endforeach;   
?>
</ul>
<h4>Добавить отзыв</h4>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'schools',
    array(
        'action' => 'view',
        'id'     => $school->id,
        'area' => null,
        'page' => null,  
    )
));
$form->setAttribute('class','')
    ->setAttribute('name', 'comment')
    ->setAttribute('id','comment')
    ->prepare();
$form->get('id')->setValue(0);
$form->get('text')->setValue('');
$form->get('text')->setAttribute('class','comment');
$form->get('submit')->setAttribute('id','submitbutton')->setValue('Сохранить');
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
if(isset($username)) :
    $form->get('author')->setValue('Администратор');
endif;
?>
<?= $this->formRow($form->get('author')); ?>
<?php include($docRoot.'/smile.html'); ?>
<br />
<?= $this->formRow($form->get('text')
    ->setAttribute('class', 'w-100')); ?>
<br />
<?php
$form->get('submit')->setAttribute('title', 'Сохранить')
        ->setAttribute('class', 'btn btn-primary my-3'); ?>
<?= $this->formSubmit($form->get('submit')); ?>
<?= $this->form()->closeTag();
